[workspace]
authors = ["Cade Mirchandani <cmirchan@ucsc.edu>"]
channels = ["conda-forge", "bioconda"]
name = "simulations"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
samtools = ">=1.22.1,<2"
python = ">=3.11.5,<3.14"
pyfastx = ">=2.2.0,<3"
art = ">=2016.6.5,<2017"
snakemake = ">=9.8.0,<10"
bwa = ">=0.7.19,<0.8"
conda = ">=25.5.1,<26"
snakefmt = ">=0.11.0,<0.12"
ipykernel = ">=6.29.5,<7"
pip = ">=25.1.1,<26"
vcftools = ">=0.1.17,<0.2"

[pypi-dependencies]
tskit = ">=0.6.4, <0.7"
stdpopsim = ">=0.3.0, <0.4"
pandas = ">=2.3.1, <3"
loguru = ">=0.7.3, <0.8"
snakemake-argparse-bridge = ">=0.1.3, <0.2"
seaborn = ">=0.13.2, <0.14"
